########################################
# MAINBOARD (LDO LEVIATHAN 1.3 - USB Katapult)
########################################
[mcu]
klipper_section: mcu
quiet_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -r -u c0d0da3a827d
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_stm32h743xx_420035000651323439333335-if00

########################################
# EBB36 (CAN - Klipper MCU)
########################################
[ebb]
klipper_section: mcu EBB
quiet_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -r -u 7069dd9adb99
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 7069dd9adb99

#[ebb]
#klipper_section: mcu EBB
#quiet_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -r -u 054bdad9e4b1
#action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 054bdad9e4b1

########################################
# CARTOGRAPHER (NON-KLIPPER FW)
########################################
[cartographer]
klipper_section: mcu scanner
is_klipper_fw: false
action_command: ~/cartographer-klipper/scripts/firmware.py -d a6811771c2f5 -f CAN